#!/bin/sh

sed -E '
    h                    # Preserve input string
    s|[^[:alnum:]_]|_|g  # Replace unacceptable characters with underscores
    s|.*|  \[key_& \]="| # Assign strings to mnemonic indices (generated with list2cstrenum)
    G                    # Append input string as value
    s|.*|&",|
    s|\n||               # Remove space after sed spaces concatenation
' |
column -s']' -o']' -t -l2
