#!/bin/sh

sed -E '
    s|[^[:alnum:]_]|_|g     # Replace unacceptable characters with underscores
    s|.*|  \[key_& \]="&",| # Assign strings to mnemonic indices (generated with list2cstrenum)
' |
column -s' ' --table

